apiVersion: v1
kind: Service
metadata:
  name: crc-bot-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: crc-bot
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http